[FilterPlugin]
; This section lists additional files which will be packaged along with your plugin. Paths should be listed relative to the root plugin directory, and
; may include "...", "*", and "?" wildcards to match directories, files, and individual characters respectively.
;
; Examples:
;    /README.txt
;    /Extras/...
;    /Binaries/ThirdParty/*.dll

/Config/FilterPlugin.ini
/Resources/Loomle/...
/Resources/LoomleToolbarIcon.png
/README.md
/LICENSE
/THIRD_PARTY_NOTICES.txt
-/Intermediate/...
