#!/usr/bin/env node

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const SCRIPT_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const INTERNAL_PACKAGE_VERSION = "0.0.0";
const MAX_CPP_INT32 = 2_147_483_647;
const SEMVER = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*)(?:\.(?:0|[1-9]\d*|\d*[A-Za-z-][0-9A-Za-z-]*))*)?(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?$/;

const paths = {
  rootPackage: "package.json",
  packageLock: "package-lock.json",
  clientPackage: "client/package.json",
  salPackage: "sal/package.json",
  interfacesPackage: "interfaces/package.json",
  generatedClientVersion: "client/src/generated/product-version.ts",
  generatedClientProtocolVersion: "client/src/generated/protocol-version.ts",
  generatedBridgeProtocolVersion: "engine/LoomleBridge/Source/LoomleBridge/Private/Generated/LoomleProtocolVersion.h",
  pluginDescriptor: "engine/LoomleBridge/LoomleBridge.uplugin",
};

async function readJson(repoRoot, relativePath) {
  const absolutePath = resolve(repoRoot, relativePath);
  try {
    return JSON.parse(await readFile(absolutePath, "utf8"));
  } catch (error) {
    throw new Error(`Cannot read ${relativePath}: ${error.message}`);
  }
}

async function readVersionMetadata(repoRoot) {
  const rootPackage = await readJson(repoRoot, paths.rootPackage);
  if (typeof rootPackage.version !== "string" || !SEMVER.test(rootPackage.version)) {
    throw new Error(
      `Invalid product version in ${paths.rootPackage}: ${JSON.stringify(rootPackage.version)}.`,
    );
  }
  const protocolVersion = rootPackage.loomle?.protocolVersion;
  if (!Number.isSafeInteger(protocolVersion)
      || protocolVersion < 1
      || protocolVersion > MAX_CPP_INT32) {
    throw new Error(
      `Invalid Client–Bridge protocol version in ${paths.rootPackage}: ${JSON.stringify(protocolVersion)}.`,
    );
  }
  return { version: rootPackage.version, protocolVersion };
}

export function renderProductVersionModule(version) {
  return [
    "// Generated by packaging/tools/product-version.mjs. Do not edit.",
    `export const productVersion: string = ${JSON.stringify(version)};`,
    "",
  ].join("\n");
}

export function renderClientProtocolVersionModule(protocolVersion) {
  return [
    "// Generated by packaging/tools/product-version.mjs. Do not edit.",
    `export const protocolVersion = ${protocolVersion} as const;`,
    "",
  ].join("\n");
}

export function renderBridgeProtocolVersionHeader(protocolVersion) {
  return [
    "// Generated by packaging/tools/product-version.mjs. Do not edit.",
    "#pragma once",
    "",
    "#include \"CoreTypes.h\"",
    "",
    "namespace Loomle::Protocol",
    "{",
    `inline constexpr int32 Version = ${protocolVersion};`,
    "}",
    "",
  ].join("\n");
}

async function writeIfChanged(path, content) {
  let current;
  try {
    current = await readFile(path, "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  if (current === content) return false;
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
  return true;
}

export async function generateProductVersion(repoRoot = SCRIPT_ROOT) {
  const { version, protocolVersion } = await readVersionMetadata(repoRoot);
  const generatedChanged = (await Promise.all([
    writeIfChanged(
      resolve(repoRoot, paths.generatedClientVersion),
      renderProductVersionModule(version),
    ),
    writeIfChanged(
      resolve(repoRoot, paths.generatedClientProtocolVersion),
      renderClientProtocolVersionModule(protocolVersion),
    ),
    writeIfChanged(
      resolve(repoRoot, paths.generatedBridgeProtocolVersion),
      renderBridgeProtocolVersionHeader(protocolVersion),
    ),
  ])).some(Boolean);

  const plugin = await readJson(repoRoot, paths.pluginDescriptor);
  if (!Number.isInteger(plugin.Version) || plugin.Version < 1) {
    throw new Error(`Invalid independent Fab build number in ${paths.pluginDescriptor}.`);
  }
  const pluginChanged = plugin.VersionName !== version;
  if (pluginChanged) {
    plugin.VersionName = version;
    await writeFile(
      resolve(repoRoot, paths.pluginDescriptor),
      `${JSON.stringify(plugin, null, 2)}\n`,
      "utf8",
    );
  }

  return { version, protocolVersion, generatedChanged, pluginChanged };
}

function expectEqual(errors, label, actual, expected) {
  if (actual !== expected) {
    errors.push(
      `${label} is ${JSON.stringify(actual)}; expected ${JSON.stringify(expected)}.`,
    );
  }
}

export async function checkProductVersion(repoRoot = SCRIPT_ROOT) {
  const { version, protocolVersion } = await readVersionMetadata(repoRoot);
  const errors = [];

  const workspacePackages = [
    [paths.clientPackage, await readJson(repoRoot, paths.clientPackage)],
    [paths.salPackage, await readJson(repoRoot, paths.salPackage)],
    [paths.interfacesPackage, await readJson(repoRoot, paths.interfacesPackage)],
  ];
  for (const [relativePath, packageJson] of workspacePackages) {
    expectEqual(
      errors,
      `${relativePath} version`,
      packageJson.version,
      INTERNAL_PACKAGE_VERSION,
    );
  }

  const lock = await readJson(repoRoot, paths.packageLock);
  expectEqual(errors, `${paths.packageLock} root version`, lock.version, version);
  expectEqual(
    errors,
    `${paths.packageLock} root workspace version`,
    lock.packages?.[""]?.version,
    version,
  );
  for (const relativePath of ["client", "sal", "interfaces"]) {
    expectEqual(
      errors,
      `${paths.packageLock} ${relativePath} workspace version`,
      lock.packages?.[relativePath]?.version,
      INTERNAL_PACKAGE_VERSION,
    );
  }

  const expectedModule = renderProductVersionModule(version);
  let generatedModule;
  try {
    generatedModule = await readFile(resolve(repoRoot, paths.generatedClientVersion), "utf8");
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  expectEqual(errors, paths.generatedClientVersion, generatedModule, expectedModule);

  for (const [relativePath, expected] of [
    [paths.generatedClientProtocolVersion, renderClientProtocolVersionModule(protocolVersion)],
    [paths.generatedBridgeProtocolVersion, renderBridgeProtocolVersionHeader(protocolVersion)],
  ]) {
    let generated;
    try {
      generated = await readFile(resolve(repoRoot, relativePath), "utf8");
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    expectEqual(errors, relativePath, generated, expected);
  }

  const plugin = await readJson(repoRoot, paths.pluginDescriptor);
  expectEqual(errors, `${paths.pluginDescriptor} VersionName`, plugin.VersionName, version);
  if (!Number.isInteger(plugin.Version) || plugin.Version < 1) {
    errors.push(
      `${paths.pluginDescriptor} Version must be a positive independent Fab build number.`,
    );
  }

  if (errors.length > 0) {
    throw new Error(
      `Product version check failed:\n- ${errors.join("\n- ")}\n`
      + "Use npm version <version> --no-git-tag-version for product changes, "
      + "then run npm run generate:version; workspace packages must stay 0.0.0.",
    );
  }
  return version;
}

function parseArguments(argv) {
  const [command, ...rest] = argv;
  let repoRoot = SCRIPT_ROOT;
  for (let index = 0; index < rest.length; index += 1) {
    if (rest[index] !== "--repo-root" || !rest[index + 1] || index + 2 !== rest.length) {
      throw new Error("Usage: product-version.mjs <generate|check> [--repo-root <path>]");
    }
    repoRoot = resolve(rest[index + 1]);
    index += 1;
  }
  if (command !== "generate" && command !== "check") {
    throw new Error("Usage: product-version.mjs <generate|check> [--repo-root <path>]");
  }
  return { command, repoRoot };
}

async function main() {
  const { command, repoRoot } = parseArguments(process.argv.slice(2));
  if (command === "generate") {
    const result = await generateProductVersion(repoRoot);
    console.log(`Generated Loomle product version ${result.version}.`);
    return;
  }
  const version = await checkProductVersion(repoRoot);
  console.log(`Loomle product version ${version} is consistent.`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
