import { mkdir, readFile, writeFile } from "node:fs/promises";

const modules = [
  ["asset", "Find UE assets and exact Asset Paths."],
  ["blueprint", "Inspect and edit Blueprint-owned structure and finalize changes."],
  ["class", "Inspect UE Reflection and edit durable Blueprint Class Defaults."],
  ["graph", "Inspect and edit Graph Nodes, Pins, Edges, flow, and Node creation."],
  ["state_tree", "Inspect and edit authored StateTree hierarchy, bindings, and compile state."],
  ["widget", "Inspect and edit WidgetBlueprint trees, Widgets, placement, and events."],
];

const packageRoot = new URL("../", import.meta.url);
const guide = await readDocument("GUIDE.md", "SAL");
const catalog = await Promise.all(
  modules.map(async ([name, description]) => ({
    name,
    description,
    text: await readDocument(`${name}.md`, name),
  })),
);

const source = [
  "// Generated by scripts/generate-catalog.mjs. Do not edit directly.",
  'import type { SalInterface } from "@loomle/sal";',
  `export const guide: string = ${JSON.stringify(guide)};`,
  `export const catalog: readonly SalInterface[] = ${JSON.stringify(catalog, null, 2)} satisfies readonly SalInterface[];`,
].join("\n\n") + "\n";

const output = new URL("src/generated/catalog.ts", packageRoot);
await mkdir(new URL("src/generated/", packageRoot), { recursive: true });
await writeFile(output, source, "utf8");

async function readDocument(path, heading) {
  const text = await readFile(new URL(path, packageRoot), "utf8");
  if (!text.startsWith(`# ${heading}\n`)) {
    throw new Error(`${path} must begin with \"# ${heading}\".`);
  }
  if (!text.endsWith("\n")) {
    throw new Error(`${path} must end with a newline.`);
  }
  return text;
}
